[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

# ✅ Safe redirect that only affects root Netlify domain
[[redirects]]
  from = "https://rationsandrootsmeal.netlify.app/*"
  to = "https://www.rationsandrootsmeal.com/:splat"
  status = 301
  force = true
