[build]
  functions = "netlify/functions"
  publish = "."
  environment = { NODE_VERSION = "20" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "node-fetch"]
 

# ✅ Redirect only after deploy (keep internal routes working)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
