[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

# ✅ Simplified redirect to your custom domain
[[redirects]]
  from = "/*"
  to = "https://www.rationsandrootsmeal.com/:splat"
  status = 301
