[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe", "node-fetch"]

# ✅ Redirect only after deploy (keep internal routes working)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
