[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[[redirects]]
  from = "https://*.netlify.app/*"
  to = "https://www.rationsandrootsmeal.com/:splat"
  status = 301
  force = true
